### ISSUE TITLE
Create Cmdlets

### ISSUE THREAD

**Issue by dfch** [dfensgmbh/biz.dfch.PS.Git.Client#3]
Prioritise as needed 
* [x] Finish-Feature.ps1
* [x] Finish-Hotfix.ps1
* [x] Finish-Release.ps1
* [x] Get-Branch.ps1
* [x] Get-Commit.ps1
* [x] Get-Feature.ps1
* [x] Get-Hotfix.ps1
* [x] Get-Release.ps1
* [x] Get-Tag.ps1
* [x] Get-Shortlog.ps1
* [x] Init-Gitflow
* [x] Invoke-Add.ps1
* [x] Invoke-Clone.ps1
* [x] Invoke-Fetch.ps1
* [x] Invoke-Git.ps1
* [x] Invoke-Pull.ps1
* [x] Invoke-Push.ps1
* [x] Merge-Branch.ps1
* [x] New-Branch.ps1
* [x] New-Commit.ps1
* [x] New-Feature.ps1
* [x] New-Hotfix.ps1
* [x] New-Release.ps1
* [x] New-Tag.ps1
* [x] Publish-Feature.ps1
* [x] Publish-Hotfix.ps1
* [x] Publish-Release.ps1
* [x] Publish-Tag.ps1
* [x] Remove-Branch.ps1
* [x] Remove-Tag.ps1
* [x] Select-Branch.ps1
* [x] Set-Branch.ps1

**Comment by dfch** [comment]
* Invoke-Git 062cb15

**Comment by dfch** [comment]
@gaestu what is the status here? could you please check the completed items and eventually close the issue?

**Comment by dfch** [comment]
@gaestu what is the status here? could you please check the completed items and eventually close the issue?

**Comment by dfch** [comment]
there are several Cmdlets that just consist of a skeleton with empty parameter lists. Often the "Gif flow" inline help is still left inside the Cmdlets. This issue cannot be blosed.

Create separate issue per Cmdlet so we actually know whazt is implemented

**Comment by gaestu** [comment]
The get-feature / get-hotfix / get-release do not have any parameter at all (you can verify over git bash `git flow feature --help`

For description i open issue #12 

If you find more cmdlets with to less parameter let me know.
