### ISSUE TITLE
add function to execute command from other directory

### ISSUE THREAD

**Issue by gaestu** [dfensgmbh/biz.dfch.PS.Git.Client#9]
add function to execute command from other directory - pass a working directory

If your posh is in c:\temp and you will make a git command in `c:\repos\repo` like `invoke-pull`, you should have a parameter to pass the repo folder

**Comment by dfch** [comment]
@gaestu I suggest to just have it like we discussed yesterday - we switch to the repo when cloning - then the client can read the repo dir and perform the steps accordingly

no need to supply a dir in the scripts (except for clone certainly)
